if(WIN32)
    set(CAPG_BASE_DIR $ENV{CAPG_BASE_DIR})
    if(CAPG_BASE_DIR)
        include_directories(${CAPG_BASE_DIR}/include)
        link_directories(${CAPG_BASE_DIR}/lib)
        if(NOT USE_INNER_ROC_SDK)
            include_directories(${CAPG_BASE_DIR}/RocSDK/include)
            link_directories(${CAPG_BASE_DIR}/RocSDK/lib)
        endif(NOT USE_INNER_ROC_SDK)
    else(CAPG_BASE_DIR)
        message("CAPG Development Basic Libriry not installed.")
    endif(CAPG_BASE_DIR)
endif(WIN32)

