function(acmake_get_dll DLLS)
    set(ACC)
    foreach(LIB ${ARGN})
        if(NOT LIB MATCHES debug)
            if(NOT LIB MATCHES optimized)
                string(REPLACE ".lib" ".dll" DLL ${LIB})
                if(NOT EXISTS ${DLL})
                    get_filename_component(LIB_FOLDER ${LIB} PATH)
                    get_filename_component(ROOT_FOLDER ${LIB_FOLDER} PATH)
                    get_filename_component(DLL_NAME ${DLL} NAME)
                    set(DLL ${ROOT_FOLDER}/bin/${DLL_NAME})
                endif()
                if(EXISTS ${DLL})
                    list(APPEND ACC ${DLL})
                endif()
            endif()
        endif()
    endforeach()
    set(${DLLS} ${ACC} PARENT_SCOPE)
endfunction()
