function(acmake_get_dll DLLS)
    set(ACC)
    foreach(LIB ${ARGN})
        if(NOT LIB MATCHES debug)
            if(NOT LIB MATCHES optimized)
                string(REPLACE ".lib" ".dll" DLL ${LIB})
                list(APPEND ACC ${DLL})
            endif()
        endif()
    endforeach()
    set(${DLLS} ${ACC} PARENT_SCOPE)
endfunction()
