include(acmake_common)
include(acmake_assert)

# usage: acmake_mysqlpp_support(<target>)
macro(acmake_mysqlpp_support TARGET)
    acmake_assert(ACMAKE_SDK_PATH)
    find_package(MySqlpp REQUIRED PATHS "${ACMAKE_SDK_PATH}")
    include_directories(${MYSQLPP_INCLUDE_DIRS})
    target_link_libraries(${TARGET} ${MYSQLPP_LIBRARIES})
endmacro()
