macro(acmake_target_platform)
    foreach(SUFFIX WINDOWS ANDROID)
        set(ACMAKE_TARGET_PLATFORM_${SUFFIX} FALSE)
    endforeach()
    if(ANDROID)
        set(ACMAKE_TARGET_PLATFORM_ANDROID TRUE)
    else()
        set(ACMAKE_TARGET_PLATFORM_WINDOWS TRUE)
    endif()
endmacro()
