if(TARGET_FILE_PATH MATCHES exe$)
    fixup_bundle("${TARGET_FILE_PATH}" "" "${RUNTIME_DIRS}")
elseif(TARGET_FILE_PATH MATCHES lib$)
    fixup_bundle("" "${TARGET_FILE_PATH}" "${RUNTIME_DIRS}")
endif()

string(TOUPPER ${CMAKE_BUILD_TYPE} CONFIG)
get_filename_component(TARGET_FILE_DIR ${TARGET_FILE_PATH} PATH)
foreach(LIB ${RUNTIME} ${RUNTIME_${CONFIG}})
    if(IS_DIRECTORY "${LIB}")
        get_filename_component(_FOLDER_NAME ${LIB} NAME)
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory ${LIB} ${TARGET_FILE_DIR}/${_FOLDER_NAME})
    else()
        execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different ${LIB} ${TARGET_FILE_DIR})
    endif()
endforeach()
